CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  username VARCHAR(30) NOT NULL,
  firstname VARCHAR(32),
  lastname VARCHAR(32),
  phonenumber VARCHAR(24),
  email  VARCHAR(50),
  sex VARCHAR(1),
  company INTEGER NULL,
  startdate VARCHAR(16) /*start date format: YYYY-MM-DD HH:mm*/
);


CREATE TABLE companies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  name VARCHAR(30),
  phone1  VARCHAR(50),
  phone2  VARCHAR(50),
  fax  VARCHAR(50),
  address VARCHAR(128),
  taxnumber VARCHAR(100)
);

CREATE TABLE usernetwork (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  username  VARCHAR(32)
);

CREATE TABLE products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  name VARCHAR(30),
  category integer,
  description  VARCHAR(256),
  company  integer,
  photo1 varchar(64),
  photo2 varchar(64)
);
