server:
  port: 8090
  context-path: /bkda
  

#eureka:
#   client:
#      serviceUrl:
#         defaultZone: http://127.0.0.1:7821/eureka
#ribbon:
#   eureka:
#      enabled: true

#Configure Spring JPA
spring:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
    hibernate:
      dialect: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
      hbm2ddl: create-drop
      show_sql: true
      format_sql: true
      default_schema: bkda
      
bkda:
  datasource:
    type: H2
    url: jdbc:h2:file:/home/vdao/data/bkda
    username: sa
    password: 
    driverClassName: org.h2.Driver
#    defaultSchema: authbkda
    maxPoolSize: 10
    tomcat:
       max-active: 5
       max-wait: 5000
       initialSize: 10
       test-on-borrow: true        
amqp:
  port: 5672
  username: davu
  password: 123456
  vhost: /
  host: localhost

security:
  jwt:
    tokenSigninKey: 5776bf874388d3c2ab89810739275b649fe740ba12
    Issuer: bkda.com
  basic:
    enabled: false
    
logging:
  level:
    org.springframework.web: debug
    org.hibernate: error
  file: /home/vdao/data/bkda/bkda_log2.txt
    